blueprint:
  name: Zigbee2MQTT - Tuya 1-Button Scene Switch TS004F
  description: Automate your Tuya 1-Button Scene Switch (TS004F) via Zigbee2MQTT. Link - https://www.zigbee2mqtt.io/devices/TS004F.html
  domain: automation
  input:
    switch:
      name: TS004F Switch
      description: Tuya 4-Button Wireless Switch
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_one_short_press:
      name: Button 1 - Single Press
      description: Action to run on button 1 (bottom-left) single press
      default: []
      selector:
        action: null
    button_one_hold:
      name: Button 1 - Hold
      description: Action to run on button 1 (bottom-left) single press
      default: []
      selector:
        action: null
    button_one_double_press:
      name: Button 1 - Double Press
      description: Action to run on button 1 (bottom-left) single press
      default: []
      selector:
        action: null
  source_url: https://github.com/NeutralPlasma/HA_Blueprint-MOES-Scene-Button-MQTT/edit/main/zha-tuya-4-button-scene-switch-ts0044-moes.yaml
mode: single
max_exceeded: silent
variables:
  command: "{{ trigger.payload }}"
  topic: "{{ trigger.topic }}"
  switch_name: !input "switch"
  deviceName: "{{ state_attr(switch_name, 'friendly_name') }}"
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action
action:
  - choose:
      - conditions:
          - "{{ topic.split('/')[1].replace('/', '') == deviceName.split(' ')[0]
            }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ command == 'single' }}"
                sequence: !input "button_one_short_press"
              - conditions:
                  - "{{ command == 'double' }}"
                sequence: !input "button_one_double_press"
              - conditions:
                  - "{{ command == 'hold' }}"
                sequence: !input "button_one_hold"
